tab_spaces = 2
struct_variant_width = 90
array_width = 90
struct_lit_width = 90
chain_width = 90
max_width = 90
fn_call_width = 90
attr_fn_like_width = 90
single_line_if_else_max_width = 90
single_line_let_else_max_width = 90
